version: "3"


services:
  flaskrest:
    build: FlaskRest
    container_name: FlaskRest
    restart: always
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/Test
volumes:
  mongodata:
