
version: "3"


services:
  flaskrest:
    build: FlaskRest
    container_name: FlaskRest
    restart: always
    expose:
      - 8080
    depends_on:
     - mongodb
    networks:
     - frontend
     - backend

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
     - flaskrest
    networks:
     - frontend

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passw0rd
      MONGO_INITDB_DATABASE: Test
      MONGODB_DATA_DIR: /data/db
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local



