
version: "3"


services:
  flaskrest:
    build: 
      context: FlaskRest
      dockerfile: Dockerfile
    container_name: FlaskRest
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: Test
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: passw0rd
      MONGODB_HOSTNAME: mongodb
    expose:
      - 8080
    volumes:
      - appdata:/var/www
    depends_on:
     - mongodb
    networks:
     - frontend
     - backend

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
     - flaskrest
    networks:
     - frontend

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passw0rd
      MONGO_INITDB_DATABASE: Test
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local
    















