version: "3"

volumes:
  mongodb_volume:

services:
  flaskrest:
    build: FlaskRest
    container_name: FlaskRest
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_name
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
    - mongodb_volume/data/Test
    restart: always